routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\ApplicationController as ClientApplicationController;
use App\Http\Controllers\Brigade\BrigadeController as BrigadePageController;
use App\Http\Controllers\Operator\ApplicationController as OperatorApplicationController;
use App\Http\Controllers\Operator\BrigadeController as OperatorBrigadeController;
use App\Http\Controllers\Operator\OperatorController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::prefix('client')->name('client.')->group(function (){

    Route::resource('applications', ClientApplicationController::class)
        ->only(['index', 'create', 'store']);

    Route::get('applications/{user}', [ClientApplicationController::class, 'showClosedApplications'])
        ->name('applications.showClosedApplications');

    Route::put('applications/{application}/set/done', [ClientApplicationController::class, 'setDoneByClient'])
        ->name('applications.setDoneByClient');
});



Route::prefix('operator')->name('operator.')->group(function (){
    Route::resource('applications', OperatorApplicationController::class)->only(['index', 'show']);

    Route::get('applications/{user}/closed/applications',
        [OperatorApplicationController::class, 'closedApplications'])->name('applications.closedApplications');

    Route::get('applications/{user}/applications', [OperatorApplicationController::class, 'operatorApplications'])
        ->name('applications.operatorApplications');


    Route::put('applications/{application}/set', [OperatorApplicationController::class, 'setOperator'])
        ->name('applications.setOperator');


    Route::get('applications/{application}/choose/brigade',
        [OperatorApplicationController::class, 'chooseBrigade'])->name('applications.chooseBrigade');

    Route::put('applications/{application}/brigades/{brigade}',
        [OperatorApplicationController::class, 'setBrigade'])->name('applications.setBrigade');

    Route::put('applications/{application}/set/done',
        [OperatorApplicationController::class, 'setDoneByOperator'])->name('applications.setDoneByOperator');





    Route::get('brigades', [OperatorBrigadeController::class, 'index'])
        ->name('brigades.index');

    Route::resource('brigades', OperatorBrigadeController::class)
        ->except([ 'show']);

    Route::resource('users', OperatorController::class)->except('show');

    Route::get('users/brigades/members', [OperatorController::class, 'showBrigadeMembers'])
        ->name('brigades.showBrigadeMembers');
});




Route::get('brigades/{brigade}', [BrigadePageController::class, 'show'])
    ->name('brigade.show');

Route::prefix('brigade')->name('brigade.')->group(function (){
    Route::put('brigades/{application}/set/process', [BrigadePageController::class, 'setInProcess'])
        ->name('setInProcess');

    Route::put('brigades/{application}/set/done', [BrigadePageController::class, 'setDone'])
        ->name('setDone');
});

app/Http/Controllers/Client/ApplicationController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\ApplicationRequest;
use App\Models\Type;
use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ApplicationController extends Controller
{
    public function __construct()
    {
        $this->middleware(['client']);
    }

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function index(): Factory|View|\Illuminate\Foundation\Application|Application
    {

        $user = Auth::user();
        $application_types = Type::all();
        $this->authorize('viewAny', \App\Models\Application::class);
        return view('client.applications.index',
            compact('application_types', 'user')
        );
    }


    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(ApplicationRequest $request): RedirectResponse
    {
        $application = new \App\Models\Application($request->all());
        $application->user()->associate($request->user());
        $application->save();
        return back()->with('success','Новая заявка успешно создана!');
    }


    /**
     * @param User $user
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function showClosedApplications(User $user): Factory|View|\Illuminate\Foundation\Application|Application
    {
        $closed_applications = $user->applications->where('status', \App\Models\Application::DONE);
        return view('client.applications.closed_applications', compact('closed_applications'));
    }


    /**
     * @param \App\Models\Application $application
     * @return RedirectResponse
     */
    public function setDoneByClient(\App\Models\Application $application): RedirectResponse
    {
        if ($application->status === \App\Models\Application::CLOSED_BY_BRIGADE){
            $application->status = \App\Models\Application::CLOSED_BY_CLIENT;
        }

        if(!!$application->update()){
            return back()->with('success', "Ваша заявка успешно выполнена!");
        } else {
            return back()->with('error', "Ваша заявка еще не выполнена!");
        }

    }
}

app/Http/Controllers/Operator/ApplicationController.php
<?php

namespace App\Http\Controllers\Operator;

use App\Http\Controllers\Controller;
use App\Models\Application;
use App\Models\Brigade;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class ApplicationController extends Controller
{
    public function __construct()
    {
        $this->middleware(['operator']);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index(): \Illuminate\Foundation\Application|View|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $applications = Application::all();
        $brigades = Brigade::all();
        $user = Auth::user();
        $brigade_applications = Application::where('status',Application::TAKEN_BY_TEAM)
            ->get();

        $active_applications = Application::where(
            'status',
            Application::ACTIVE)
            ->get();

        $op_applications = Application::where(
            'operator_id',
            Auth::id()
        )->get();

        return view('operator.applications.index',
            compact('user',
                'applications',
                'active_applications',
                'op_applications',
                'brigades',
                'brigade_applications'
            )
        );
    }


    /**
     * @param User $user
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function closedApplications(User $user): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $closed_applications = Application::where('operator_id', $user->id)
            ->where('status', Application::DONE)->get();
        return view('operator.applications.closed_applications', compact('user', 'closed_applications' ));
    }


    /**
     * @param Application $application
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function show(Application $application): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $user = $application->user;
        return view('operator.applications.show', compact('application', 'user'));
    }


    /**
     * @param User $user
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function operatorApplications(User $user): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $op_applications = Application::where('operator_id', Auth::id())->get();
        return view('operator.applications.op_applications', compact('op_applications', 'user'));
    }


    /**
     * @param Application $application
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function chooseBrigade(Application $application): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $brigades = Brigade::all();
        return view('operator.applications.brigades', compact('brigades', 'application'))
            ->with('Бригада назначена!');
    }


    /**
     * @param Application $application
     * @return RedirectResponse
     */
    public function setOperator(Application $application): RedirectResponse
    {
        $user = Auth::user();
        $application->status = Application::TAKEN_BY_OPERATOR;
        $application->operator_id = $user->id;
        $application->update();
        return redirect(route('operator.applications.operatorApplications', compact('user')))
            ->with('success', 'Заявка у оператора!');
    }


    /**
     * @param Application $application
     * @param Brigade $brigade
     * @return RedirectResponse
     */
    public function setBrigade( Application $application, Brigade $brigade):RedirectResponse
    {
        $application->status = Application::TAKEN_BY_TEAM;
        $application->brigade_id = $brigade->id;
        $application->update();
        return redirect(route('operator.applications.index'))
            ->with('success', "Заявка передана бригаде $brigade->name!");
    }

    /**
     * @param Application $application
     * @return RedirectResponse
     */
    public function setDoneByOperator(Application $application): RedirectResponse
    {
        if($application->status === Application::CLOSED_BY_CLIENT) {
            $application->status = Application::DONE;
            $application->update();
            return back()
                ->with('success',
                    'Заявка выполнена!');
        } else {
            return back()
                ->with('error',
                    'Ещё не вся работа сделана, пожалуйста отметьте эту задачу когда бригада и клиент отметят её как выполненную!');
        }
    }
}

app/Http/Controllers/Operator/BrigadeController.php
<?php

namespace App\Http\Controllers\Operator;

use App\Http\Controllers\Controller;
use App\Http\Requests\BrigadeRequest;
use App\Models\Brigade;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class BrigadeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['operator']);
    }


    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index(): \Illuminate\Foundation\Application|View|Factory|Application
    {
        $brigades = Brigade::all();
        return view('operator.brigades.index', compact('brigades' ));
    }


    /**
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function create(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        $brigade_members = User::where('role_id', 3)->get();
        return view('operator.brigades.create', compact('brigade_members'));
    }


    /**
     * @param BrigadeRequest $request
     * @return RedirectResponse
     */
    public function store(BrigadeRequest $request): RedirectResponse
    {
        // надо исправить
        $brigade = new Brigade();
        $brigade->name = $request->input('name');
        $brigade->save();
        $brigade_id = $brigade->id;
        $user_ids = $request->input('user_id');
        User::whereIn('id', $user_ids)->update(['brigade_id' => $brigade_id]);

        return redirect(route('operator.brigades.index'))->with('success', 'Новая бригада успешно создана!');
    }


    /**
     * @param Brigade $brigade
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function edit(Brigade $brigade): \Illuminate\Foundation\Application|View|Factory|Application
    {
        $brigade_members = User::where('role_id', 3)->get();
        return view('operator.brigades.edit', compact('brigade', 'brigade_members'));
    }


    /**
     * @param BrigadeRequest $request
     * @param Brigade $brigade
     * @return RedirectResponse
     */
    public function update(BrigadeRequest $request, Brigade $brigade):RedirectResponse
    {
        $brigade->update($request->all());
        return redirect(route('operator.brigades.showBrigadeMembers'))
            ->with('success', "Информация о бригаде успешно обновлена!");
    }


    /**
     * @param Brigade $brigade
     * @return RedirectResponse
     */
    public function destroy(Brigade $brigade): RedirectResponse
    {
        $brigade->delete();
        return back();
    }
}

app/Http/Controllers/Operator/OperatorController.php
<?php

namespace App\Http\Controllers\Operator;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class OperatorController extends Controller
{
    /**
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function index(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        $operators = User::where('role_id', 1)->get();
        return view('operator.operators.index', compact('operators'));
    }


    /**
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function create(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        $staff_roles = Role::whereIn('id', [1,3])->get();
        return view('operator.operators.create', compact('staff_roles'));
    }


    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $operator = new User($request->all());
        $operator->save();
        return redirect(route('operator.users.store'))
            ->with('success', "Новый член тех поддержки успешно добавлен!");;  // написать сообщение
    }


    /**
     * @param User $user
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function edit(User $user): Factory|View|\Illuminate\Foundation\Application|Application
    {
        return view('operator.operators.edit', compact('user'));
    }


    /**
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(Request $request, User $user): RedirectResponse
    {
        $user->update($request->all());
        return redirect(route('operator.users.index'))->with('success', "Информация об операторе успешно обновлена!");

    }


    /**
     * @param User $user
     * @return RedirectResponse
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();
        return back()->with('success', "Оператор успешно удален!");
    }


    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function showBrigadeMembers(): \Illuminate\Foundation\Application|View|Factory|Application
    {
        $brigade_members = User::where('role_id', 3)->get();
        return view('operator.brigades.brigade_members', compact('brigade_members'));
    }
}

resources/views/operator/applications/brigades.blade.php
@extends('layouts.operator')
@section('content')
    <div class="container mt-4">
        <div class="row">
            <h3>Бригады</h3>
        </div>
        <div class="mt-4">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Название</th>
                    <th>Статус</th>
                    <th>Действие</th>
                </tr>
                </thead>
                <tbody>
                @foreach($brigades as $brigade)
                    <tr>
                        <td>{{$brigade->id}}</td>
                        <td>{{$brigade->name}}</td>
                        <td>{{$brigade->status}}</td>
                        <td>
                            <form action="{{ route('operator.applications.setBrigade', ['brigade' => $brigade, 'application' => $application]) }}" method="post">
                                @method('put')
                                @csrf
                                <button class="btn btn-success press-btn" type="submit">Назначить</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/operator/applications/closed_applications.blade.php
@extends('layouts.operator')

@section('content')
    <div class="container mt-4">
        @include('notifications.alerts')

        <div class="row links mb-5">
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.index')}}">
                    <p>Все заявки /</p>
                </a>
            </div>
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.operatorApplications', ['user' => $user]) }}">
                    <p>Мои заявки /</p>
                </a>
            </div>

            <div class="col-sm-2">
                <a href="{{ route('operator.applications.closedApplications', ['user' => $user]) }}">
                    <p>Закрытые заявки /</p>
                </a>
            </div>
        </div>

        <h3>Закрытые заявки</h3>
        <table class="table table-hover mt-5">
            <thead>
            <tr>
                <th>#</th>
                <th>Заявка</th>
                <th>Бригада</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
            @foreach($closed_applications as $application)
                <tr>
                    <td>{{ $application->id }}</td>
                    <td>{{ $application->type->name}}</td>
                    <td>{{ $application->brigade->name}}</td>
                    <td>{{ $application->getStatusForOperator()}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/operator/applications/index.blade.php
@extends('layouts.operator')

@section('content')

    <div class="container mt-4">
        @include('notifications.alerts')

        <div class="row links mb-5">
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.index')}}">
                    <p>Все заявки /</p>
                </a>
            </div>
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.operatorApplications', ['user' => $user]) }}">
                    <p>Мои заявки /</p>
                </a>
            </div>

            <div class="col-sm-2">
                <a href="{{ route('operator.applications.closedApplications', ['user' => $user]) }}">
                    <p>Закрытые заявки /</p>
                </a>
            </div>
        </div>
        @if(count($active_applications))
                <div class="row mt-5">
                    <div class="col">
                        <h3>Все новые заявки</h3>
                    </div>
                </div>
                <div class="row all-appl-block mt-4">
                    <div class="col">
                        <table class="table table-borderless">
                            <thead>
                                <tr>
                                    <th>Заявка</th>
                                    <th>Дата создания</th>
                                    <th>Действия</th>
                                </tr>
                            </thead>
                        <tbody>
                            @foreach($active_applications as $application)
                                <tr>
                                    <td>
                                        <a href="{{ route('operator.applications.show', ['application' => $application]) }}">
                                            {{$application->type->name}}
                                        </a>
                                    </td>
                                    <td>{{ $application->created_at}}</td>
                                    <td>
                                        <form
                                            action="{{ route('operator.applications.setOperator', ['application' => $application]) }}"
                                            method="post">
                                            @csrf
                                            @method('put')
                                            <button class="btn press-btn" type="submit">Начать работу</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            @else
                <h3>Новых заявок пока нет</h3>
           @endif
        <h4 class="brigade-appl">Заявки переданные бригадам</h4>
        <br>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Заявка</th>
                <th>Бригада</th>
            </tr>
            </thead>
            <tbody>
            @foreach($brigade_applications as $application)
                <tr>
                    <td>{{ $application->type->name}}</td>
                    <td>{{ $application->brigade->name}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection

resources/views/operator/applications/op_applications.blade.php
@extends('layouts.operator')
@section('content')

    <div class="container mt-4">
        @include('notifications.alerts')

        <div class="row links mb-5">
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.index')}}">
                    <p>Все заявки /</p>
                </a>
            </div>
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.operatorApplications', ['user' => $user]) }}">
                    <p>Мои заявки /</p>
                </a>
            </div>

            <div class="col-sm-2">
                <a href="{{ route('operator.applications.closedApplications', ['user' => $user]) }}">
                    <p>Закрытые заявки /</p>
                </a>
            </div>
        </div>

        <div class="my-appl-block mt-4">
            <h3 class="mb-4">Мои заявки</h3>
            <div class="col">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Заявка</th>
                        <th>Статус</th>
                        <th>Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($op_applications as $application)
                        @if($application->statusIsNotDone())
                            <tr>
                                <td>
                                    <a href="{{ route('operator.applications.show', ['application' => $application]) }}">
                                        {{$application->type->name}}
                                    </a>
                                </td>
                                <td>{{ $application->getStatusForOperator()}}</td>
                                <td>
                                    @if($application->canSetBrigade())
                                        <a class="btn btn-success press-btn" href="{{ route('operator.applications.chooseBrigade', ['application' => $application]) }}">Назначить бригаду</a>
                                    @endif

                                    @if($application->canSetDone())
                                        <form action="{{route('operator.applications.setDoneByOperator', ['application' => $application])}}" method="post">
                                            @method('put')
                                            @csrf
                                            <button class="btn btn-success press-btn" type="submit">Отметить как выполнненное</button>
                                        </form>
                                    @endif
                                </td>
                            </tr>
                        @endif
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/operator/applications/show.blade.php
@extends('layouts.operator')
@section('content')
    <div class="container mt-4">

        <div class="row links mb-5">
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.index')}}">
                    <p>Все заявки</p>
                </a>
            </div>
            <div class="col-sm-2">
                <a href="{{ route('operator.applications.operatorApplications', ['user' => $user]) }}">
                    <p>Мои заявки</p>
                </a>
            </div>

            <div class="col-sm-2">
                <a href="{{ route('operator.applications.closedApplications', ['user' => $user]) }}">
                    <p>Закрытые заявки /</p>
                </a>
            </div>
        </div>

        <h3>Подробнее о заявке</h3>

        <table class="table table-hover mt-5 mb-5">
            <thead>
            <tr>
                <th>Заявка</th>
                <th>Комментарий</th>
                <th>Дата открытия</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $application->type->name }}</td>
                    <td>{{ $application->comment }}</td>
                    <td>{{ $application->created_at }}</td>
                    <td>{{ $application->getStatusForOperator()}}</td>
                </tr>
            </tbody>
        </table>

        <h5 class="headline mb-3">Информация о клиенте:</h5>
        <div class="row client-info-block">
            <div class="col-12 col-lg-6 ">
                <ul>
                    <li><strong>Имя:  </strong> {{$application->user->name}}</li>
                    <li><strong>Номер телефона:  </strong>{{$application->user->phone_number}}</li>
                    <li><strong>Адрес:  </strong>{{$application->user->address}}</li>
                    <li><strong>Почта:  </strong>{{$application->user->email}}</li>
                </ul>
            </div>
        </div>
    </div>
@endsection