routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\ApplicationController as ClientApplicationController;
use App\Http\Controllers\Brigade\BrigadeController as BrigadePageController;
use App\Http\Controllers\Operator\ApplicationController as OperatorApplicationController;
use App\Http\Controllers\Operator\BrigadeController as OperatorBrigadeController;
use App\Http\Controllers\Operator\OperatorController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::prefix('client')->name('client.')->group(function (){

    Route::resource('applications', ClientApplicationController::class)
        ->only(['index', 'create', 'store']);

    Route::get('applications/{user}', [ClientApplicationController::class, 'showClosedApplications'])
        ->name('applications.showClosedApplications');

    Route::put('applications/{application}/set/done', [ClientApplicationController::class, 'setDoneByClient'])
        ->name('applications.setDoneByClient');
});



Route::prefix('operator')->name('operator.')->group(function (){
    Route::resource('applications', OperatorApplicationController::class)->only(['index', 'show']);

    Route::get('applications/{user}/closed/applications',
        [OperatorApplicationController::class, 'closedApplications'])->name('applications.closedApplications');

    Route::get('applications/{user}/applications', [OperatorApplicationController::class, 'operatorApplications'])
        ->name('applications.operatorApplications');


    Route::put('applications/{application}/set', [OperatorApplicationController::class, 'setOperator'])
        ->name('applications.setOperator');


    Route::get('applications/{application}/choose/brigade',
        [OperatorApplicationController::class, 'chooseBrigade'])->name('applications.chooseBrigade');

    Route::put('applications/{application}/brigades/{brigade}',
        [OperatorApplicationController::class, 'setBrigade'])->name('applications.setBrigade');

    Route::put('applications/{application}/set/done',
        [OperatorApplicationController::class, 'setDoneByOperator'])->name('applications.setDoneByOperator');





    Route::get('brigades', [OperatorBrigadeController::class, 'index'])
        ->name('brigades.index');

    Route::resource('brigades', OperatorBrigadeController::class)
        ->except([ 'show']);

    Route::resource('users', OperatorController::class)->except('show');

    Route::get('users/brigades/members', [OperatorController::class, 'showBrigadeMembers'])
        ->name('brigades.showBrigadeMembers');
});




Route::get('brigades/{brigade}', [BrigadePageController::class, 'show'])
    ->name('brigade.show');

Route::prefix('brigade')->name('brigade.')->group(function (){
    Route::put('brigades/{application}/set/process', [BrigadePageController::class, 'setInProcess'])
        ->name('setInProcess');

    Route::put('brigades/{application}/set/done', [BrigadePageController::class, 'setDone'])
        ->name('setDone');
});

app/Models/Brigade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Brigade extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'status'];

    /**
     * @return HasMany
     */
    public function users(): HasMany
    {
        return $this->hasMany(User::class);
    }


    /**
     * @return HasMany
     */
    public function applications(): HasMany
    {
        return $this->hasMany(Application::class);
    }
}

app/Http/Controllers/Brigade/BrigadeController.php
<?php

namespace App\Http\Controllers\Brigade;

use App\Http\Controllers\Controller;
use App\Models\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class BrigadeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['brigade']);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function show(): Factory|View|\Illuminate\Foundation\Application|\Illuminate\Contracts\Foundation\Application
    {
        $user = Auth::user();
        $brigade = $user->brigade;
        return view('brigade.show', compact( 'brigade', 'user'));
    }


    /**
     * @param Application $application
     * @return RedirectResponse
     */
    public function setInProcess(Application $application): RedirectResponse
    {
        $application->status = Application::IN_PROGRESS;
        $application->update();
        return back();
    }

    /**
     * @param Application $application
     * @return RedirectResponse
     */
    public function setDone(Application $application): RedirectResponse
    {
        $application->status = Application::CLOSED_BY_BRIGADE;
        $application->update();
        return back();
    }
}

app/Http/Controllers/Operator/ApplicationController.php
<?php

namespace App\Http\Controllers\Operator;

use App\Http\Controllers\Controller;
use App\Models\Application;
use App\Models\Brigade;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class ApplicationController extends Controller
{
    public function __construct()
    {
        $this->middleware(['operator']);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index(): \Illuminate\Foundation\Application|View|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $applications = Application::all();
        $brigades = Brigade::all();
        $user = Auth::user();
        $brigade_applications = Application::where('status',Application::TAKEN_BY_TEAM)
            ->get();

        $active_applications = Application::where(
            'status',
            Application::ACTIVE)
            ->get();

        $op_applications = Application::where(
            'operator_id',
            Auth::id()
        )->get();

        return view('operator.applications.index',
            compact('user',
                'applications',
                'active_applications',
                'op_applications',
                'brigades',
                'brigade_applications'
            )
        );
    }


    /**
     * @param User $user
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function closedApplications(User $user): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $closed_applications = Application::where('operator_id', $user->id)
            ->where('status', Application::DONE)->get();
        return view('operator.applications.closed_applications', compact('user', 'closed_applications' ));
    }


    /**
     * @param Application $application
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function show(Application $application): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $user = $application->user;
        return view('operator.applications.show', compact('application', 'user'));
    }


    /**
     * @param User $user
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function operatorApplications(User $user): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $op_applications = Application::where('operator_id', Auth::id())->get();
        return view('operator.applications.op_applications', compact('op_applications', 'user'));
    }


    /**
     * @param Application $application
     * @return View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
     */
    public function chooseBrigade(Application $application): View|\Illuminate\Foundation\Application|Factory|\Illuminate\Contracts\Foundation\Application
    {
        $brigades = Brigade::all();
        return view('operator.applications.brigades', compact('brigades', 'application'))
            ->with('Бригада назначена!');
    }


    /**
     * @param Application $application
     * @return RedirectResponse
     */
    public function setOperator(Application $application): RedirectResponse
    {
        $user = Auth::user();
        $application->status = Application::TAKEN_BY_OPERATOR;
        $application->operator_id = $user->id;
        $application->update();
        return redirect(route('operator.applications.operatorApplications', compact('user')))
            ->with('success', 'Заявка у оператора!');
    }


    /**
     * @param Application $application
     * @param Brigade $brigade
     * @return RedirectResponse
     */
    public function setBrigade( Application $application, Brigade $brigade):RedirectResponse
    {
        $application->status = Application::TAKEN_BY_TEAM;
        $application->brigade_id = $brigade->id;
        $application->update();
        return redirect(route('operator.applications.index'))
            ->with('success', "Заявка передана бригаде $brigade->name!");
    }

    /**
     * @param Application $application
     * @return RedirectResponse
     */
    public function setDoneByOperator(Application $application): RedirectResponse
    {
        if($application->status === Application::CLOSED_BY_CLIENT) {
            $application->status = Application::DONE;
            $application->update();
            return back()
                ->with('success',
                    'Заявка выполнена!');
        } else {
            return back()
                ->with('error',
                    'Ещё не вся работа сделана, пожалуйста отметьте эту задачу когда бригада и клиент отметят её как выполненную!');
        }
    }
}

app/Http/Controllers/Operator/BrigadeController.php
<?php

namespace App\Http\Controllers\Operator;

use App\Http\Controllers\Controller;
use App\Http\Requests\BrigadeRequest;
use App\Models\Brigade;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class BrigadeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['operator']);
    }


    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index(): \Illuminate\Foundation\Application|View|Factory|Application
    {
        $brigades = Brigade::all();
        return view('operator.brigades.index', compact('brigades' ));
    }


    /**
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function create(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        $brigade_members = User::where('role_id', 3)->get();
        return view('operator.brigades.create', compact('brigade_members'));
    }


    /**
     * @param BrigadeRequest $request
     * @return RedirectResponse
     */
    public function store(BrigadeRequest $request): RedirectResponse
    {
        // надо исправить
        $brigade = new Brigade();
        $brigade->name = $request->input('name');
        $brigade->save();
        $brigade_id = $brigade->id;
        $user_ids = $request->input('user_id');
        User::whereIn('id', $user_ids)->update(['brigade_id' => $brigade_id]);

        return redirect(route('operator.brigades.index'))->with('success', 'Новая бригада успешно создана!');
    }


    /**
     * @param Brigade $brigade
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function edit(Brigade $brigade): \Illuminate\Foundation\Application|View|Factory|Application
    {
        $brigade_members = User::where('role_id', 3)->get();
        return view('operator.brigades.edit', compact('brigade', 'brigade_members'));
    }


    /**
     * @param BrigadeRequest $request
     * @param Brigade $brigade
     * @return RedirectResponse
     */
    public function update(BrigadeRequest $request, Brigade $brigade):RedirectResponse
    {
        $brigade->update($request->all());
        return redirect(route('operator.brigades.showBrigadeMembers'))
            ->with('success', "Информация о бригаде успешно обновлена!");
    }


    /**
     * @param Brigade $brigade
     * @return RedirectResponse
     */
    public function destroy(Brigade $brigade): RedirectResponse
    {
        $brigade->delete();
        return back();
    }
}

app/Http/Controllers/Operator/OperatorController.php
<?php

namespace App\Http\Controllers\Operator;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class OperatorController extends Controller
{
    /**
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function index(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        $operators = User::where('role_id', 1)->get();
        return view('operator.operators.index', compact('operators'));
    }


    /**
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function create(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        $staff_roles = Role::whereIn('id', [1,3])->get();
        return view('operator.operators.create', compact('staff_roles'));
    }


    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $operator = new User($request->all());
        $operator->save();
        return redirect(route('operator.users.store'))
            ->with('success', "Новый член тех поддержки успешно добавлен!");;  // написать сообщение
    }


    /**
     * @param User $user
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function edit(User $user): Factory|View|\Illuminate\Foundation\Application|Application
    {
        return view('operator.operators.edit', compact('user'));
    }


    /**
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(Request $request, User $user): RedirectResponse
    {
        $user->update($request->all());
        return redirect(route('operator.users.index'))->with('success', "Информация об операторе успешно обновлена!");

    }


    /**
     * @param User $user
     * @return RedirectResponse
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();
        return back()->with('success', "Оператор успешно удален!");
    }


    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function showBrigadeMembers(): \Illuminate\Foundation\Application|View|Factory|Application
    {
        $brigade_members = User::where('role_id', 3)->get();
        return view('operator.brigades.brigade_members', compact('brigade_members'));
    }
}

resources/views/operator/brigades/brigade_members.blade.php
@extends('layouts.operator')
@section('content')
    <div class="container mt-4">
        @include('notifications.alerts')
        <div class="row links mb-5">
            <div >
                <a href="{{ route('operator.users.create') }}">Добавить специалиста по технической поддержке</a>
            </div>
        </div>
        <div class="row">
            <h3>Бригада</h3>
        </div>
        <div class="mt-4 mb-5">
            <table class="table">
                <thead>
                <tr>
                    <th>Имя</th>
                    <th>Email</th>
                    <th>Изменить</th>
                    <th>Удалить</th>
                </tr>
                </thead>
                <tbody>
                @foreach($brigade_members as $user)
                    <tr>
                        <td>{{$user->name}}</td>
                        <td>{{$user->email}}</td>
                        <td>
                            <a class="btn btn-sm btn-outline-success press-btn" href="{{route('operator.users.edit', ['user' => $user])}}">Изменить</a>
                        </td>
                        <td>
                            <form action="{{route('operator.users.destroy', ['user' => $user])}}" method="post">
                                @method('delete')
                                @csrf
                                <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/operator/brigades/create.blade.php
@extends('layouts.operator')

@section('content')
    <div class="container mt-4">

        <div class="row mt-4">
            <form action="{{route('operator.brigades.store')}}" method="post">
                @csrf

                <div class="row mb-3">
                    <label for="name" class="col-md-4 col-form-label text-md-end">{{ __('Название бригады') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="members" class="col-md-4 col-form-label text-md-end">{{ __('Члены бригады') }}</label>
                    <div class="col-md-6">
                        <select name="user_id[]" class="form-select @error('name') is-invalid @enderror " multiple aria-label="multiple select example">
                            <option selected>Выберите члена бригады</option>
                            @foreach($brigade_members as $member)
                                <option value="{{$member->id}}">{{$member->name}}</option>
                            @endforeach
                        </select>
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-success press-btn">
                            Создать бригаду
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/operator/brigades/edit.blade.php
@extends('layouts.operator')
@section('content')
    <div class="container mt-4">

        <div class="row mt-4">
            <form action="{{route('operator.brigades.update', ['brigade'=> $brigade])}}" method="post">
                @method('put')
                @csrf

                <div class="row mb-3">
                    <label for="name" class="col-md-4 col-form-label text-md-end">{{ __('Название бригады') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $brigade->name }}" required autocomplete="name" autofocus>

                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="members" class="col-md-4 col-form-label text-md-end">{{ __('Члены бригады') }}</label>
                    <div class="col-md-6">
                        <select name="user_id[]" class="form-select @error('name') is-invalid @enderror " multiple aria-label="multiple select example">
                            <option>Выберите члена бригады</option>
                            @foreach($brigade_members as $member)
                                <option value="{{$member->id}}" @if($member->brigade_id == $brigade->id) selected @endif>{{$member->name}}</option>
                            @endforeach
                        </select>
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-success press-btn">
                            Сохранить изменения
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/operator/brigades/index.blade.php
@extends('layouts.operator')
@section('content')
    <div class="container mt-4">
        @include('notifications.alerts')

        <div class="row links mb-5">
            <div class="col-sm-2">
                <a href="{{ route('operator.brigades.create') }}">Создать бригаду</a>
            </div>
            <div class="col-sm-2">
                <a href="{{ route('operator.brigades.showBrigadeMembers') }}">Все члены бригад</a>
            </div>
        </div>

        <div class="row">
            <h3>Бригады</h3>
        </div>

        <div class="mt-4 mb-5">
            <table class="table">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Статус</th>
                    <th>Изменить</th>
                    <th>Удалить</th>
                </tr>
                </thead>
                <tbody>
                @foreach($brigades as $brigade)
                    <tr>
                        <td>{{$brigade->name}}</td>
                        <td>{{$brigade->status}}</td>
                        <td>
                            <a class="btn btn-sm btn-success press-btn" href="{{ route('operator.brigades.edit', ['brigade' => $brigade]) }}">Изменить</a>
                        </td>
                        <td>
                            <form action="{{ route('operator.brigades.destroy', ['brigade' => $brigade]) }}" method="post">
                                @method('delete')
                                @csrf
                                <button class="btn btn-sm btn-danger delete-btn" type="submit">Удалить</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection